---
title: "first-analysis"
author: "Tim Marchand"
date: "2021-03-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
# start by deciding the number of pages to scrape
fivethirtyeight_slack_pages <- tibble(page_num = 1:25)
#add the page urls of articles to scrape 
fivethirtyeight_slack_pages <- fivethirtyeight_slack_pages %>% 
  mutate(page = paste0("https://fivethirtyeight.com/tag/slack-chat/page/", page_num, "/"))
```

```{r}
fivethirtyeight_slack_pages
#Create a function to grab the links
get_links <- function(page){
  page <- read_html(page)
  page %>% 
    html_nodes("#main .entry-title a") %>%
    html_attr("href") %>% 
    as_tibble() %>% 
    rename("links" = "value")
}
#Scrape the links and add to tibble
fivethirtyeight_slack_pages <- fivethirtyeight_slack_pages %>% 
  mutate(links = map(page, get_links))
```

Create function with progress report

```{r}
library(progress)
# unnest links to expand tibble
fivethirtyeight_slack_pages <- fivethirtyeight_slack_pages %>% 
  unnest(links)
pb <- progress_bar$new(total = nrow(fivethirtyeight_slack_pages),
                       format = "executing [:bar] :percent eta::eta")
#Create a function to extract text
get_text <- function(link){
  
  pb$tick()
  Sys.sleep(1/100)
  
  link <- read_html(link)
  link %>% 
    html_nodes(".single-post-content p") %>% 
    html_text() %>% 
    # replace all first mentions to unify the speaker names
  str_replace_all(pattern = " \\([^:]+?\\):",replacement = ":") %>% 
    as_tibble() %>% 
  rename(comment = value) %>% 
    # remove the text from extra links 
  filter(!str_detect(comment,"\\[Related")) %>% 
    # find all texts starting with speaker:
  mutate(header = str_detect(.$comment,"^[a-z.]+: ")) %>% 
    # count the turns of each speaker using cumsum on header
    mutate(turn = cumsum(.$header)) %>% 
    # collapse turns into one text row
     group_by(turn) %>% 
  summarise(text = str_c(comment, collapse = "\n")) %>% 
  # create speaker column and text column, separating on the first :
    separate(text,c("speaker", "text"), sep = ":", extra = "merge") %>% 
  filter(turn > 0)
}
```

Apply the function and scrape
```{r}
#Scrape the actual text
#Progress bar is shown in console
fivethirtyeight_slack_pages <- fivethirtyeight_slack_pages %>% 
  mutate(results = map(links, get_text))

  
```

Show the first 20 unnested results

```{r}

fivethirtyeight_slack_pages %>% 
  unnest(results) %>% 
  select(links, everything(), -c(page_num,page)) %>% 
  extract(col = links,into = "topic","https://fivethirtyeight.com/features/([^/]+)") %>% 
  mutate(topic = snakecase::to_sentence_case(topic)) %>% 
  head(20)
```